name: GCP Deploy

on:
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Lint
        id: lint-step
        run: npm run lint
      - name: check-lint
        if: failure() && steps.lint-step.outcome == 'failure'
        run: echo "Código precisa ser revisto!!"

  build_docker:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          dockerfile: ./Dockerfile # Certifique-se de que o caminho do seu Dockerfile está correto
          tags: alicia1983/webacademy:latest

  deploy:
    needs: build_docker
    runs-on: ubuntu-latest
    environment: wagcp_deploy
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/webacademy:latest
    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v3

      # Login to GCP
      - name: Login to GCP
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      # gcloud configure docker
      - name: Configure Docker to use GCR
        run: gcloud auth configure-docker --quiet

      # Build Docker image
      - name: Build Docker image for GCP
        run: docker build -t $IMAGE_NAME .

      # Push image to Google Container Registry (GCR)
      - name: Push Docker image to GCR
        run: docker push $IMAGE_NAME

      # Deploy Docker image to Google Cloud Run
      - name: Deploy Docker image to Google Cloud Run
        run: |
          gcloud run deploy wacicd \
            --image $IMAGE_NAME \
            --region us-west1 \
            --memory 128Mi \
            --min-instances 0 \
            --max-instances 1 \
            --platform managed \
            --port 8080 \
            --allow-unauthenticated
